Algoritmo "semnome"



Var

glicose, normal, elevado, diabetes : real

Inicio

escreval("Digite a medida da glicose : ")
leia(glicose)

    se glicose <= 100.0 entao
      escreval("Classificação : Normal")
    senao
       se glicose s<= 140.0 entao
       escreval("Classificação : Elevado")
    senao
       escreval("Classificação : Diabetes")
  fimse
fimse


  
  



Fimalgoritmo